systemLog:
  destination: file
  path: "/var/log/mongodb/newagroyug.log"
  logAppend: true
storage:
  engine: wiredTiger
  dbPath: "/data/newagroyug"
  journal:
    enabled: true
processManagement:
  fork: true
net:
  bindIp: 127.0.0.1,127.0.1.1
  port: 13888
replication:
  replSetName: 'newagroyug'
